### ISSUE TITLE
Loading data locally fails when the s3 extension is loaded

### ISSUE THREAD

**Issue by fhennig** [stackabletech/druid-operator#71]
I've noticed this problem here and have alread reported it [upstream](https://github.com/apache/druid/issues/12039), I wanted to document the problem in our repo as well.

TLDR: If the s3 extension is loaded but not actually used (local deep storage, loading data locally) errors appear that a connection to s3 cannot be made.

We could possibly add a switch to decide whether the extension should be loaded or not. If proper credentials are provided as well, it works.

There is however a feature where you load s3 data from a bucket with credentials that you just provide in the Web UI. To allow this ad-hoc s3 access, the extension must be loaded at all times. If we instead provide a switch in the CRD whether it should be loaded or not, that's not possible anymore.

**Comment by lfrancke** [comment]
Let's look at this together because the error messages do indeed seem like JDK 9+ is used

**Comment by fhennig** [comment]
I reproduced the error also using our current docker image (commit hash  b641321) which uses OpenJDK 1.8.0 (https://github.com/stackabletech/docker-images/blob/main/druid/Dockerfile#L10). So I'm pretty sure it's JDK 8, but I might have overlooked something as well. If someone else could reproduce/not reproduce this we might find out more.

**Comment by maltesander** [comment]
I did reproduce that. Ill mention it upstream as well (the ticket was somehow ignored and pointed to use java 8 - which we did). Otherwise i talked to @fhennig and we need to add some sort of switch e.g.:
- load s3 extensions when s3 secret is provided (then loading local data works)
- do not load the s3 extension if no s3 secret is provided (then local data loading works but we cannot load data via s3)

**Comment by lfrancke** [comment]
I'm happy to help out with debugging if needed.

**Comment by maltesander** [comment]
Yeah as i learned the switch is a bad solution since we could set the s3 credentials via the UI (so we basically always want the s3-extension to be activated). I would say we wait a little more and check if anything happens upstream, otherwise we need to debug and do it ourselves.

**Comment by adwk67** [comment]
I noticed this while debugging this issue:

![image](https://user-images.githubusercontent.com/1712947/155570243-205bc9f5-818a-49a1-8a2d-e2b376859227.png)

Apparently the SDK looks for `awssdk_config_override.json` on the classpath and if doesn't find it, goes ahead with s3. Maybe providing that file could help.

**Comment by adwk67** [comment]
The issue seems to be that Druid exposes an interface [DruidModule](https://github.com/apache/druid/blob/druid-0.22.1/core/src/main/java/org/apache/druid/initialization/DruidModule.java#L29-L33) : the HdfsStorageDruidModule just does some simple [mapping](https://github.com/apache/druid/blob/druid-0.22.1/extensions-core/hdfs-storage/src/main/java/org/apache/druid/storage/hdfs/HdfsStorageDruidModule.java#L64-L73), whereas the S3StorageDruidModule [registers](https://github.com/apache/druid/blob/druid-0.22.1/extensions-core/s3-extensions/src/main/java/org/apache/druid/storage/s3/S3StorageDruidModule.java#L134) a type which includes checking some [predconditions](https://github.com/apache/druid/blob/druid-0.22.1/extensions-core/s3-extensions/src/main/java/org/apache/druid/storage/s3/S3LoadSpec.java#L51-L52): this happens on [initialization](https://github.com/apache/druid/blob/druid-0.22.1/server/src/main/java/org/apache/druid/initialization/Initialization.java#L508) which is triggered by list of extensions registered as a runtime properties.

The documentation lists the order in which the [credential provider chain](https://druid.apache.org/docs/latest/development/extensions-core/s3.html#s3-authentication-methods) is resolved: instead of providing a default/dummy s3 credential in our CRs, we can supply this once in the common runtime properties and then override it either via a manual ingestion specification entered in the console UI, or via the existing s3-spec in the cluster definition.

What will be tested/implemented:

- [ ] run quickstart tutorial successfully with the s3-extension included in the extension list and the runtime properties extended to include placeholder values like this:

```
druid.s3.accessKey=YOURKEYGOESHERE
druid.s3.secretKey=YOURKEYGOESHERE
druid.s3.endpoint.url=YOURURLGOESHERE
```
- [ ] with the same setup as above, load from a s3 bucket by providing credentials in the ingestion-spec
- [ ] refactor operator code to add these entries to runtime properties
- [ ] test with a S3-relevant and non-S3-relevant CR2
